server.port: 8081
application:
  title: User Service
  version: v1.0
captcha:
  length: 3
  clearCacheRate: 5 #min

spring:
  datasource:
    url:
    username:
    password:

  security:
    user:
      name: admin
      password: 12345678
    oauth2:
      client:
        registration:
          github:
            clientId: CREATE!!!
            clientSecret: CREATE!!!
            authorizationGrantType: authorization_code
            redirectUri: http://109.184.122.25:8080/oauth2/callback/github
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
            userInfoUri: https://api.github.com/user
            userNameAttribute: id
  liquibase:
    enabled: false

jwt:
  secret: 3255526a4b323074654133697a626c6e67634b3333586c7a64425a79666e4676
  token-validity-min: 15
  refresh-token-validity: 7 #days

